CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_device_id TEXT DEFAULT '',
    actor_member_id BIGINT NULL,
    actor_member_name TEXT DEFAULT '',
    actor_permission TEXT DEFAULT '',
    action TEXT NOT NULL,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    status_code INTEGER,
    target_table TEXT DEFAULT '',
    target_id TEXT DEFAULT '',
    request_id TEXT DEFAULT '',
    user_agent TEXT DEFAULT '',
    ip_address TEXT DEFAULT '',
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_device_id ON audit_logs(actor_device_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_member_id ON audit_logs(actor_member_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_path ON audit_logs(path);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_name TEXT NOT NULL,
    permission_key TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (role_name, permission_key)
);

INSERT INTO role_permissions (role_name, permission_key, enabled)
VALUES
    ('システム管理者', 'system:admin', TRUE),
    ('システム管理者', 'admin:write', TRUE),
    ('システム管理者', 'recordings:manage', TRUE),
    ('システム管理者', 'scores:manage', TRUE),
    ('管理者', 'admin:write', TRUE),
    ('管理者', 'recordings:manage', TRUE),
    ('管理者', 'scores:manage', TRUE),
    ('会計', 'payments:manage', TRUE),
    ('インペク', 'schedules:manage', TRUE),
    ('パートリーダー', 'part:manage', TRUE),
    ('録音係', 'recordings:manage', TRUE),
    ('楽譜係', 'scores:manage', TRUE),
    ('団員', 'portal:read', TRUE)
ON CONFLICT (role_name, permission_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS cache_invalidation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key TEXT NOT NULL,
    reason TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cache_invalidation_events_created_at ON cache_invalidation_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cache_invalidation_events_cache_key ON cache_invalidation_events(cache_key);
