CREATE TABLE IF NOT EXISTS performance_day_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id TEXT NOT NULL DEFAULT 'default',
    performance_id BIGINT NULL REFERENCES performances(id) ON DELETE CASCADE,
    timeline TEXT DEFAULT '',
    timeline_rows JSONB NOT NULL DEFAULT '[]'::jsonb,
    costume_detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    costume TEXT DEFAULT '',
    assignments_rows JSONB NOT NULL DEFAULT '[]'::jsonb,
    assignments TEXT DEFAULT '',
    timetable TEXT DEFAULT '',
    duties TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_performance_day_infos_org_id ON performance_day_infos(organization_id);
CREATE INDEX IF NOT EXISTS idx_performance_day_infos_org_id_id ON performance_day_infos(organization_id, id);
CREATE INDEX IF NOT EXISTS idx_performance_day_infos_performance_id ON performance_day_infos(performance_id);
