CREATE TABLE IF NOT EXISTS flyer_distributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id TEXT NOT NULL DEFAULT 'default',
    facility_name TEXT DEFAULT '',
    area_address TEXT DEFAULT '',
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flyer_distributions_org_id ON flyer_distributions(organization_id);
CREATE INDEX IF NOT EXISTS idx_flyer_distributions_org_id_id ON flyer_distributions(organization_id, id);
CREATE INDEX IF NOT EXISTS idx_flyer_distributions_facility_name ON flyer_distributions(facility_name);
