CREATE TABLE IF NOT EXISTS flyer_distribution_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id TEXT NOT NULL DEFAULT 'default',
    performance_id BIGINT,
    flyer_distribution_id BIGINT,
    planned_member_id BIGINT,
    planned_member_name TEXT DEFAULT '',
    planned_date DATE,
    distributed_member_id BIGINT,
    distributed_member_name TEXT DEFAULT '',
    distributed_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flyer_distribution_assignments_org_id ON flyer_distribution_assignments(organization_id);
CREATE INDEX IF NOT EXISTS idx_flyer_distribution_assignments_org_id_id ON flyer_distribution_assignments(organization_id, id);
CREATE INDEX IF NOT EXISTS idx_flyer_distribution_assignments_perf ON flyer_distribution_assignments(performance_id);
CREATE INDEX IF NOT EXISTS idx_flyer_distribution_assignments_dist ON flyer_distribution_assignments(flyer_distribution_id);
