CREATE TABLE IF NOT EXISTS concert_record_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id TEXT NOT NULL DEFAULT 'default',
    performance_id BIGINT NOT NULL REFERENCES performances(id) ON DELETE CASCADE,
    youtube_url TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_concert_record_videos_org_id ON concert_record_videos(organization_id);
CREATE INDEX IF NOT EXISTS idx_concert_record_videos_org_id_id ON concert_record_videos(organization_id, id);
CREATE INDEX IF NOT EXISTS idx_concert_record_videos_performance_id ON concert_record_videos(performance_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_concert_record_videos_org_performance_sort
    ON concert_record_videos(organization_id, performance_id, sort_order);
