CREATE TABLE IF NOT EXISTS improvement_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id TEXT NOT NULL DEFAULT 'default',
    member_id BIGINT NULL,
    registered_by TEXT NOT NULL DEFAULT '',
    suggestion TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT '未対応',
    resolution TEXT NOT NULL DEFAULT '',
    responded_at DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_improvement_suggestions_status
        CHECK (status IN ('未対応', '修正中', '対応済')),
    CONSTRAINT chk_improvement_suggestions_text
        CHECK (length(trim(suggestion)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_improvement_suggestions_org_id
    ON improvement_suggestions (organization_id);

CREATE INDEX IF NOT EXISTS idx_improvement_suggestions_org_status_created
    ON improvement_suggestions (organization_id, status, created_at DESC);
