CREATE TABLE IF NOT EXISTS portal_notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id TEXT NOT NULL DEFAULT 'default',
    date DATE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_by_member_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_portal_notices_title CHECK (length(trim(title)) > 0),
    CONSTRAINT chk_portal_notices_content CHECK (length(trim(content)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_portal_notices_org_id
    ON portal_notices (organization_id);

CREATE INDEX IF NOT EXISTS idx_portal_notices_org_created
    ON portal_notices (organization_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_portal_notices_org_creator
    ON portal_notices (organization_id, created_by_member_id);
