from __future__ import annotations

import os
from typing import Any, Callable

from fastapi import HTTPException

from .db_schema import (
    DB_BOOL_COLUMNS,
    DB_CHILD_COLUMNS,
    DB_COLLECTION_COLUMNS,
    DB_DATE_COLUMNS,
    DB_INT_COLUMNS,
    DB_JSON_COLUMNS,
    DB_MONTH_COLUMNS,
    DB_NUMERIC_COLUMNS,
    DB_TIME_COLUMNS,
    DB_TIMESTAMP_COLUMNS,
    PORTAL_DB_TABLES,
)


def db_data_enabled(psycopg: Any, psql: Any) -> bool:
    if psycopg is None or psql is None:
        return False
    if os.getenv("DB_URL", "").strip():
        return True
    return all(os.getenv(name, "").strip() for name in ("DB_HOST", "DB_NAME", "DB_USER", "DB_PASSWORD"))


def env_flag_enabled(name: str) -> bool:
    return str(os.getenv(name, "")).strip().lower() in {"1", "true", "yes", "on"}


def local_json_fallback_enabled(env_flag_enabled_func: Callable[[str], bool] = env_flag_enabled) -> bool:
    """Return True only when local JSON fallback is explicitly requested."""

    data_backend = os.getenv("DATA_BACKEND", "db").strip().lower()
    if data_backend in {"local", "json", "file", "files"}:
        return True
    return env_flag_enabled_func("LOCAL_JSON_FALLBACK_ENABLED")


def db_expected(
    local_json_fallback_enabled_func: Callable[[], bool] = local_json_fallback_enabled,
    env_flag_enabled_func: Callable[[str], bool] = env_flag_enabled,
) -> bool:
    if env_flag_enabled_func("DB_REQUIRED"):
        return True
    # If any DB connection hint exists, prefer DB-expected mode for safety.
    if any(
        os.getenv(name, "").strip()
        for name in ("DB_URL", "DB_HOST", "DB_NAME", "DB_USER", "DB_PASSWORD")
    ):
        return True
    if local_json_fallback_enabled_func():
        return False
    # The portal now treats DB as the default data backend.
    return True


def ensure_db_expected_is_ready(
    db_expected_func: Callable[[], bool],
    db_data_enabled_func: Callable[[], bool],
) -> None:
    if db_expected_func() and not db_data_enabled_func():
        raise HTTPException(
            status_code=500,
            detail="DB is expected but not ready. Set DB_URL or DB_HOST/DB_NAME/DB_USER/DB_PASSWORD. "
            "For emergency local development only, set DATA_BACKEND=local.",
        )


def ensure_db_schema_compatibility(conn: Any) -> None:
    with conn.cursor() as cur:
        for table_name in sorted(PORTAL_DB_TABLES - {"portal_json_collections"}):
            columns = DB_COLLECTION_COLUMNS.get(table_name) or DB_CHILD_COLUMNS.get(table_name)
            if not columns:
                continue
            cur.execute(_db_create_table_sql(table_name, columns))
            cur.execute(
                f"ALTER TABLE {_db_ident(table_name)} "
                "ADD COLUMN IF NOT EXISTS organization_id TEXT NOT NULL DEFAULT 'default'"
            )
            for column in columns:
                if column == "id":
                    continue
                cur.execute(
                    f"ALTER TABLE {_db_ident(table_name)} "
                    f"ADD COLUMN IF NOT EXISTS {_db_ident(column)} {_db_column_type(table_name, column, for_create=False)}"
                )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS {_db_ident('idx_' + table_name + '_org_id')} "
                f"ON {_db_ident(table_name)} (organization_id)"
            )
            if "id" in columns:
                cur.execute(
                    f"CREATE INDEX IF NOT EXISTS {_db_ident('idx_' + table_name + '_org_id_id')} "
                    f"ON {_db_ident(table_name)} (organization_id, id)"
                )
        cur.execute(
            "ALTER TABLE performances ADD COLUMN IF NOT EXISTS performance_fee_amount NUMERIC(12, 2) NOT NULL DEFAULT 0"
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS access_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
                member_name TEXT DEFAULT '',
                member_part TEXT DEFAULT '',
                permission TEXT DEFAULT '',
                menu_key TEXT NOT NULL,
                menu_label TEXT NOT NULL,
                panel TEXT DEFAULT '',
                device_id TEXT DEFAULT '',
                device_name TEXT DEFAULT '',
                user_agent TEXT DEFAULT '',
                accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cur.execute("CREATE INDEX IF NOT EXISTS idx_access_logs_accessed_at ON access_logs(accessed_at DESC)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_access_logs_member_id ON access_logs(member_id)")
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS portal_json_collections (
                collection_name TEXT PRIMARY KEY,
                items JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_portal_json_collections_updated_at "
            "ON portal_json_collections(updated_at DESC)"
        )


def _db_ident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _db_column_type(table_name: str, column: str, *, for_create: bool) -> str:
    if column == "id":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if for_create else "BIGINT"
    if column in {"created_at", "updated_at"}:
        return "TIMESTAMPTZ NOT NULL DEFAULT NOW()"
    if column in DB_INT_COLUMNS.get(table_name, set()):
        return "BIGINT"
    if column in DB_BOOL_COLUMNS.get(table_name, set()):
        return "BOOLEAN NOT NULL DEFAULT FALSE"
    if column in DB_NUMERIC_COLUMNS.get(table_name, set()):
        return "NUMERIC(12, 2) NOT NULL DEFAULT 0"
    if column in DB_DATE_COLUMNS.get(table_name, set()):
        return "DATE"
    if column in DB_TIME_COLUMNS.get(table_name, set()):
        return "TIME"
    if column in DB_TIMESTAMP_COLUMNS.get(table_name, set()):
        return "TIMESTAMPTZ"
    if column in DB_MONTH_COLUMNS.get(table_name, set()):
        return "CHAR(7) DEFAULT ''"
    if column in DB_JSON_COLUMNS.get(table_name, set()):
        default = "'{}'::jsonb" if table_name == "performance_day_infos" and column == "costume_detail" else "'[]'::jsonb"
        return f"JSONB NOT NULL DEFAULT {default}"
    return "TEXT DEFAULT ''"


def _db_create_table_sql(table_name: str, columns: tuple[str, ...]) -> str:
    column_definitions = []
    if "organization_id" not in columns:
        column_definitions.append("organization_id TEXT NOT NULL DEFAULT 'default'")
    for column in columns:
        column_definitions.append(f"{_db_ident(column)} {_db_column_type(table_name, column, for_create=True)}")
    return f"CREATE TABLE IF NOT EXISTS {_db_ident(table_name)} ({', '.join(column_definitions)})"


def run_db_startup_self_check(
    *,
    db_expected_func: Callable[[], bool],
    ensure_db_expected_is_ready_func: Callable[[], None],
    assert_db_ready_func: Callable[[], None],
    psycopg: Any,
    db_connection_string_func: Callable[[], str],
    ensure_db_schema_compatibility_func: Callable[[Any], None] = ensure_db_schema_compatibility,
) -> None:
    if not db_expected_func():
        return

    ensure_db_expected_is_ready_func()
    assert_db_ready_func()

    try:
        with psycopg.connect(db_connection_string_func(), autocommit=True) as conn:
            ensure_db_schema_compatibility_func(conn)
            with conn.cursor() as cur:
                cur.execute("SELECT 1")
                cur.fetchone()
                cur.execute("SELECT to_regclass('public.members')")
                row = cur.fetchone()
                if not row or row[0] is None:
                    raise RuntimeError("members table does not exist")
    except HTTPException:
        raise
    except Exception as exc:
        raise RuntimeError(f"DB startup self-check failed: {exc}") from exc
