from __future__ import annotations

import os
from typing import Any, Callable

from fastapi import HTTPException


def db_data_enabled(psycopg: Any, psql: Any) -> bool:
    if psycopg is None or psql is None:
        return False
    if os.getenv("DB_URL", "").strip():
        return True
    return all(os.getenv(name, "").strip() for name in ("DB_HOST", "DB_NAME", "DB_USER", "DB_PASSWORD"))


def env_flag_enabled(name: str) -> bool:
    return str(os.getenv(name, "")).strip().lower() in {"1", "true", "yes", "on"}


def local_json_fallback_enabled(env_flag_enabled_func: Callable[[str], bool] = env_flag_enabled) -> bool:
    """Return True only when local JSON fallback is explicitly requested."""

    data_backend = os.getenv("DATA_BACKEND", "db").strip().lower()
    if data_backend in {"local", "json", "file", "files"}:
        return True
    return env_flag_enabled_func("LOCAL_JSON_FALLBACK_ENABLED")


def db_expected(
    local_json_fallback_enabled_func: Callable[[], bool] = local_json_fallback_enabled,
    env_flag_enabled_func: Callable[[str], bool] = env_flag_enabled,
) -> bool:
    if env_flag_enabled_func("DB_REQUIRED"):
        return True
    # If any DB connection hint exists, prefer DB-expected mode for safety.
    if any(
        os.getenv(name, "").strip()
        for name in ("DB_URL", "DB_HOST", "DB_NAME", "DB_USER", "DB_PASSWORD")
    ):
        return True
    if local_json_fallback_enabled_func():
        return False
    # The portal now treats DB as the default data backend.
    return True


def ensure_db_expected_is_ready(
    db_expected_func: Callable[[], bool],
    db_data_enabled_func: Callable[[], bool],
) -> None:
    if db_expected_func() and not db_data_enabled_func():
        raise HTTPException(
            status_code=500,
            detail="DB is expected but not ready. Set DB_URL or DB_HOST/DB_NAME/DB_USER/DB_PASSWORD. "
            "For emergency local development only, set DATA_BACKEND=local.",
        )


def ensure_db_schema_compatibility(conn: Any) -> None:
    with conn.cursor() as cur:
        cur.execute(
            "ALTER TABLE performances ADD COLUMN IF NOT EXISTS performance_fee_amount NUMERIC(12, 2) NOT NULL DEFAULT 0"
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS access_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
                member_name TEXT DEFAULT '',
                member_part TEXT DEFAULT '',
                permission TEXT DEFAULT '',
                menu_key TEXT NOT NULL,
                menu_label TEXT NOT NULL,
                panel TEXT DEFAULT '',
                device_id TEXT DEFAULT '',
                device_name TEXT DEFAULT '',
                user_agent TEXT DEFAULT '',
                accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cur.execute("CREATE INDEX IF NOT EXISTS idx_access_logs_accessed_at ON access_logs(accessed_at DESC)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_access_logs_member_id ON access_logs(member_id)")
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS portal_json_collections (
                collection_name TEXT PRIMARY KEY,
                items JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_portal_json_collections_updated_at "
            "ON portal_json_collections(updated_at DESC)"
        )


def run_db_startup_self_check(
    *,
    db_expected_func: Callable[[], bool],
    ensure_db_expected_is_ready_func: Callable[[], None],
    assert_db_ready_func: Callable[[], None],
    psycopg: Any,
    db_connection_string_func: Callable[[], str],
    ensure_db_schema_compatibility_func: Callable[[Any], None] = ensure_db_schema_compatibility,
) -> None:
    if not db_expected_func():
        return

    ensure_db_expected_is_ready_func()
    assert_db_ready_func()

    try:
        with psycopg.connect(db_connection_string_func(), autocommit=True) as conn:
            ensure_db_schema_compatibility_func(conn)
            with conn.cursor() as cur:
                cur.execute("SELECT 1")
                cur.fetchone()
                cur.execute("SELECT to_regclass('public.members')")
                row = cur.fetchone()
                if not row or row[0] is None:
                    raise RuntimeError("members table does not exist")
    except HTTPException:
        raise
    except Exception as exc:
        raise RuntimeError(f"DB startup self-check failed: {exc}") from exc
