from __future__ import annotations

PORTAL_DB_TABLES = {
    "portal_json_collections",
    "performances",
    "performance_pieces",
    "performance_day_infos",
    "schedules",
    "announcements",
    "events",
    "members",
    "auth_devices",
    "access_logs",
    "absences",
    "event_responses",
    "date_adjustments",
    "date_adjustment_candidates",
    "date_adjustment_responses",
    "piece_infos",
    "practice_instructions",
    "castings",
    "casting_members",
    "casting_extras",
    "payments",
    "payment_performance_fees",
    "flyer_places",
    "flyer_distributions",
    "desired_pieces",
    "desired_piece_votes",
    "promotions",
    "albums",
    "album_photos",
    "part_settings",
    "venue_settings",
    "org_settings",
    "sns_settings",
    "connection_settings",
    "drive_files",
    "recording_metadata",
    "sheet_library",
}

JSON_COLLECTION_TABLES = {
    "performances": "performances",
    "schedules": "schedules",
    "announcements": "announcements",
    "events": "events",
    "members": "members",
    "auth_devices": "auth_devices",
    "access_logs": "access_logs",
    "absences": "absences",
    "event_responses": "event_responses",
    "date_adjustments": "date_adjustments",
    "date_adjustment_responses": "date_adjustment_responses",
    "piece_infos": "piece_infos",
    "practice_instructions": "practice_instructions",
    "performance_day_infos": "performance_day_infos",
    "payments": "payments",
    "flyer_places": "flyer_places",
    "flyer_distributions": "flyer_distributions",
    "castings": "castings",
    "desired_pieces": "desired_pieces",
    "promotions": "promotions",
    "albums": "albums",
    "part_settings": "part_settings",
    "venue_settings": "venue_settings",
    "org_settings": "org_settings",
    "sns_settings": "sns_settings",
    "connection_settings": "connection_settings",
    "drive_files": "drive_files",
    "recording_metadata": "recording_metadata",
    "sheet_library": "sheet_library",
}

DB_WRITABLE_COLLECTIONS = set(JSON_COLLECTION_TABLES)

DB_COLLECTION_COLUMNS = {
    "performances": (
        "id",
        "title",
        "date",
        "open_time",
        "start_time",
        "venue",
        "conductor",
        "flyer_image",
        "performance_fee_amount",
        "created_at",
        "updated_at",
    ),
    "schedules": (
        "id",
        "date",
        "time",
        "start_time",
        "end_time",
        "venue",
        "available_hours",
        "available_start_time",
        "available_end_time",
        "performance_id",
        "performance_title",
        "pieces",
        "is_conductor_training",
        "is_main_performance",
        "notes",
        "created_at",
        "updated_at",
    ),
    "announcements": ("id", "date", "title", "content", "created_at", "updated_at"),
    "events": ("id", "title", "date", "start_time", "deadline", "url", "notes", "delete_phrase", "fee", "created_at", "updated_at"),
    "members": (
        "id",
        "name",
        "last_name",
        "first_name",
        "maiden_name",
        "last_name_kana",
        "first_name_kana",
        "maiden_name_kana",
        "part",
        "photo_url",
        "is_founder",
        "is_recording_manager",
        "is_sheet_manager",
        "password",
        "permission",
        "joined_at",
        "system_access_until",
        "introducer",
        "role",
        "instrument_history",
        "past_orchestras",
        "comment",
        "created_at",
        "updated_at",
    ),
    "auth_devices": (
        "id",
        "device_id",
        "device_name",
        "member_id",
        "member_name",
        "member_part",
        "permission",
        "system_access_until",
        "is_recording_manager",
        "is_sheet_manager",
        "hidden_user",
        "user_agent",
        "authenticated_at",
        "last_seen_at",
        "created_at",
        "updated_at",
    ),
    "access_logs": (
        "id",
        "member_id",
        "member_name",
        "member_part",
        "permission",
        "menu_key",
        "menu_label",
        "panel",
        "device_id",
        "device_name",
        "user_agent",
        "accessed_at",
        "created_at",
        "updated_at",
    ),
    "absences": ("id", "schedule_id", "member_id", "name", "status", "note", "created_at", "updated_at"),
    "event_responses": ("id", "event_id", "member_id", "name", "status", "note", "created_at", "updated_at"),
    "date_adjustments": ("id", "title", "deadline", "notes", "delete_phrase", "created_by", "member_id", "created_at", "updated_at"),
    "date_adjustment_responses": ("id", "adjustment_id", "candidate_key", "member_id", "name", "status", "note", "created_at", "updated_at"),
    "piece_infos": ("id", "performance_id", "piece", "description", "created_at", "updated_at"),
    "practice_instructions": ("id", "performance_id", "piece", "practice_notes", "performance_instruction", "created_at", "updated_at"),
    "performance_day_infos": (
        "id",
        "performance_id",
        "timeline",
        "timeline_rows",
        "costume_detail",
        "costume",
        "assignments_rows",
        "assignments",
        "timetable",
        "duties",
        "created_at",
        "updated_at",
    ),
    "payments": (
        "id",
        "member_id",
        "name",
        "paid_from_month",
        "paid_until_month",
        "latest_payment_date",
        "membership_fee_amount",
        "created_at",
        "updated_at",
    ),
    "flyer_places": (
        "id",
        "performance_id",
        "performance_title",
        "place_name",
        "area",
        "note",
        "created_at",
        "updated_at",
    ),
    "flyer_distributions": (
        "id",
        "performance_id",
        "performance_title",
        "flyer_place_id",
        "flyer_place_name",
        "flyer_place_area",
        "flyer_place_note",
        "planned_member_id",
        "planned_member_name",
        "planned_date",
        "executed_member_id",
        "executed_member_name",
        "executed_date",
        "created_at",
        "updated_at",
    ),
    "castings": ("id", "performance_id", "piece", "created_at", "updated_at"),
    "desired_pieces": (
        "id",
        "title",
        "piece",
        "composer",
        "duration",
        "genre",
        "formation",
        "notes",
        "member_id",
        "registered_by",
        "created_at",
        "updated_at",
    ),
    "promotions": ("id", "title", "summary", "image_url", "member_id", "registered_by", "created_at", "updated_at"),
    "albums": ("id", "event_name", "created_by_member_id", "created_by_member_name", "created_at", "updated_at"),
    "part_settings": ("id", "name", "sort_order", "is_active", "created_at", "updated_at"),
    "venue_settings": ("id", "name", "address", "for_practice", "for_performance", "notes", "sort_order", "created_at", "updated_at"),
    "org_settings": (
        "id",
        "organization_name",
        "organization_abbreviation",
        "short_name",
        "icon_url",
        "membership_fee_amount",
        "created_at",
        "updated_at",
    ),
    "sns_settings": ("id", "line_url", "x_url", "instagram_url", "youtube_url", "facebook_url", "website_url", "extra_links", "created_at", "updated_at"),
    "connection_settings": (
        "id",
        "google_project_id",
        "google_cloud_storage_bucket",
        "google_cloud_storage_data_prefix",
        "google_cloud_storage_public",
        "google_service_account_file",
        "google_service_account_json",
        "created_at",
        "updated_at",
    ),
    "drive_files": ("id", "source", "object_name", "path", "name", "url", "size_bytes", "mime_type", "created_at", "updated_at"),
    "recording_metadata": (
        "id",
        "source",
        "object_name",
        "path",
        "name",
        "date",
        "piece",
        "duration_seconds",
        "duration",
        "mime_type",
        "size_bytes",
        "created_at",
        "updated_at",
    ),
    "sheet_library": (
        "id",
        "performance_id",
        "performance_title",
        "piece",
        "part",
        "source",
        "name",
        "path",
        "object_name",
        "url",
        "view_url",
        "download_url",
        "size_bytes",
        "mime_type",
        "created_at",
        "updated_at",
    ),
}

DB_DATE_COLUMNS = {
    "performances": {"date"},
    "schedules": {"date"},
    "announcements": {"date"},
    "events": {"date"},
    "members": {"joined_at", "system_access_until"},
    "auth_devices": {"system_access_until"},
    "date_adjustments": {"deadline"},
    "date_adjustment_candidates": {"date"},
    "payments": {"latest_payment_date"},
    "flyer_distributions": {"planned_date", "executed_date"},
    "recording_metadata": {"date"},
}

DB_TIME_COLUMNS = {
    "performances": {"open_time", "start_time"},
    "schedules": {"start_time", "end_time", "available_start_time", "available_end_time"},
    "events": {"start_time"},
    "date_adjustment_candidates": {"start_time", "end_time"},
}

DB_TIMESTAMP_COLUMNS = {
    "events": {"deadline"},
    "members": {"created_at", "updated_at"},
    "auth_devices": {"authenticated_at", "last_seen_at", "created_at", "updated_at"},
    "access_logs": {"accessed_at", "created_at", "updated_at"},
    "desired_piece_votes": {"voted_at", "created_at", "updated_at"},
    "album_photos": {"uploaded_at", "created_at", "updated_at"},
}

DB_NUMERIC_COLUMNS = {
    "payments": {"membership_fee_amount"},
    "payment_performance_fees": {"fee_amount"},
    "performances": {"performance_fee_amount"},
    "org_settings": {"membership_fee_amount"},
    "recording_metadata": {"duration_seconds"},
}

DB_INT_COLUMNS = {
    "performances": {"id"},
    "schedules": {"id", "performance_id"},
    "announcements": {"id"},
    "events": {"id"},
    "members": {"id"},
    "auth_devices": {"id", "member_id"},
    "access_logs": {"id", "member_id"},
    "absences": {"id", "schedule_id", "member_id"},
    "event_responses": {"id", "event_id", "member_id"},
    "date_adjustments": {"id", "member_id"},
    "date_adjustment_responses": {"id", "adjustment_id", "member_id"},
    "piece_infos": {"id", "performance_id"},
    "practice_instructions": {"id", "performance_id"},
    "performance_day_infos": {"id", "performance_id"},
    "payments": {"id", "member_id"},
    "flyer_places": {"id", "performance_id"},
    "flyer_distributions": {"id", "performance_id", "flyer_place_id", "planned_member_id", "executed_member_id"},
    "castings": {"id", "performance_id"},
    "desired_pieces": {"id", "member_id"},
    "promotions": {"id", "member_id"},
    "albums": {"id", "created_by_member_id"},
    "part_settings": {"id", "sort_order"},
    "venue_settings": {"id", "sort_order"},
    "org_settings": {"id"},
    "sns_settings": {"id"},
    "connection_settings": {"id"},
    "drive_files": {"id", "size_bytes"},
    "recording_metadata": {"id", "size_bytes"},
    "sheet_library": {"id", "performance_id", "size_bytes"},
    "performance_pieces": {"id", "performance_id", "sort_order"},
    "date_adjustment_candidates": {"id", "adjustment_id", "sort_order"},
    "casting_members": {"id", "casting_id", "member_id", "sort_order"},
    "casting_extras": {"id", "casting_id", "sort_order"},
    "payment_performance_fees": {"payment_id", "performance_id"},
    "desired_piece_votes": {"id", "desired_piece_id", "member_id"},
    "album_photos": {"id", "album_id", "uploaded_by_member_id"},
}

DB_BOOL_COLUMNS = {
    "performance_pieces": {"is_encore"},
    "schedules": {"is_conductor_training", "is_main_performance"},
    "members": {"is_founder", "is_recording_manager", "is_sheet_manager"},
    "auth_devices": {"is_recording_manager", "is_sheet_manager", "hidden_user"},
    "payment_performance_fees": {"is_paid"},
    "part_settings": {"is_active"},
    "venue_settings": {"for_practice", "for_performance"},
    "connection_settings": {"google_cloud_storage_public"},
}

DB_MONTH_COLUMNS = {
    "payments": {"paid_from_month", "paid_until_month"},
}

DB_JSON_COLUMNS = {
    "performance_day_infos": {"timeline_rows", "costume_detail", "assignments_rows"},
    "sns_settings": {"extra_links"},
}

DB_CHILD_TABLES = {
    "performances": ("performance_pieces",),
    "date_adjustments": ("date_adjustment_candidates",),
    "payments": ("payment_performance_fees",),
    "castings": ("casting_members", "casting_extras"),
    "desired_pieces": ("desired_piece_votes",),
    "albums": ("album_photos",),
}

DB_CHILD_PARENT_KEYS = {
    "performance_pieces": "performance_id",
    "date_adjustment_candidates": "adjustment_id",
    "payment_performance_fees": "payment_id",
    "casting_members": "casting_id",
    "casting_extras": "casting_id",
    "desired_piece_votes": "desired_piece_id",
    "album_photos": "album_id",
}

DB_CHILD_COLUMNS = {
    "performance_pieces": ("id", "performance_id", "sort_order", "title", "alias", "part", "composer", "duration", "is_encore", "created_at", "updated_at"),
    "date_adjustment_candidates": ("id", "adjustment_id", "candidate_key", "date", "start_time", "end_time", "note", "sort_order", "created_at", "updated_at"),
    "payment_performance_fees": ("payment_id", "performance_id", "is_paid", "fee_amount", "created_at", "updated_at"),
    "casting_members": ("id", "casting_id", "member_id", "part", "sort_order", "created_at", "updated_at"),
    "casting_extras": ("id", "casting_id", "name", "furigana", "part", "sort_order", "created_at", "updated_at"),
    "desired_piece_votes": ("id", "desired_piece_id", "member_id", "name", "voted_at", "created_at", "updated_at"),
    "album_photos": (
        "id",
        "album_id",
        "filename",
        "url",
        "object_name",
        "path",
        "uploaded_by_member_id",
        "uploaded_by_member_name",
        "uploaded_at",
        "created_at",
        "updated_at",
    ),
}

DB_COLLECTION_ORDER_BY = {
    "part_settings": "sort_order",
    "venue_settings": "sort_order",
}
