-- PostgreSQL schema draft for Orchestra Portal
-- Version: 1.0 (initial design)
-- Note: This file defines database-first tables for non-binary business data.

BEGIN;

-- =========================
-- Core master tables
-- =========================

CREATE TABLE IF NOT EXISTS performances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date DATE,
    open_time TIME,
    start_time TIME,
    venue TEXT,
    conductor TEXT,
    flyer_image TEXT DEFAULT '',
    performance_fee_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS performance_pieces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT NOT NULL REFERENCES performances(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    title TEXT NOT NULL,
    alias TEXT DEFAULT '',
    composer TEXT DEFAULT '',
    is_encore BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (performance_id, sort_order)
);

CREATE INDEX IF NOT EXISTS idx_performance_pieces_performance_id ON performance_pieces(performance_id);

CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    time TEXT DEFAULT '',
    start_time TIME,
    end_time TIME,
    venue TEXT DEFAULT '',
    available_hours TEXT DEFAULT '',
    available_start_time TIME,
    available_end_time TIME,
    performance_id BIGINT REFERENCES performances(id) ON DELETE SET NULL,
    performance_title TEXT DEFAULT '',
    pieces TEXT DEFAULT '',
    is_conductor_training BOOLEAN NOT NULL DEFAULT FALSE,
    is_main_performance BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(date);
CREATE INDEX IF NOT EXISTS idx_schedules_performance_id ON schedules(performance_id);

CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    title TEXT DEFAULT '',
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_announcements_date ON announcements(date DESC);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date DATE,
    start_time TIME,
    deadline TIMESTAMPTZ,
    url TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    delete_phrase TEXT DEFAULT '',
    fee TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_date ON events(date DESC);

CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '',
    last_name TEXT DEFAULT '',
    first_name TEXT DEFAULT '',
    maiden_name TEXT DEFAULT '',
    last_name_kana TEXT DEFAULT '',
    first_name_kana TEXT DEFAULT '',
    maiden_name_kana TEXT DEFAULT '',
    part TEXT DEFAULT '',
    photo_url TEXT DEFAULT '',
    is_founder BOOLEAN NOT NULL DEFAULT FALSE,
    is_recording_manager BOOLEAN NOT NULL DEFAULT FALSE,
    is_sheet_manager BOOLEAN NOT NULL DEFAULT FALSE,
    password TEXT DEFAULT '',
    permission TEXT NOT NULL DEFAULT '一般',
    joined_at DATE,
    system_access_until DATE,
    introducer TEXT DEFAULT '',
    role TEXT DEFAULT '',
    instrument_history TEXT DEFAULT '',
    past_orchestras TEXT DEFAULT '',
    comment TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (permission IN ('一般', '管理者', 'システム管理者', 'エキストラ'))
);

CREATE INDEX IF NOT EXISTS idx_members_name ON members(name);
CREATE INDEX IF NOT EXISTS idx_members_part ON members(part);

CREATE TABLE IF NOT EXISTS auth_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL UNIQUE,
    device_name TEXT DEFAULT '',
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    member_name TEXT DEFAULT '',
    member_part TEXT DEFAULT '',
    permission TEXT DEFAULT '一般',
    system_access_until DATE,
    is_recording_manager BOOLEAN NOT NULL DEFAULT FALSE,
    is_sheet_manager BOOLEAN NOT NULL DEFAULT FALSE,
    hidden_user BOOLEAN NOT NULL DEFAULT FALSE,
    user_agent TEXT DEFAULT '',
    authenticated_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auth_devices_member_id ON auth_devices(member_id);

-- =========================
-- Extra collections
-- =========================

CREATE TABLE IF NOT EXISTS absences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT REFERENCES schedules(id) ON DELETE SET NULL,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    name TEXT DEFAULT '',
    status TEXT DEFAULT '',
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_absences_schedule_id ON absences(schedule_id);
CREATE INDEX IF NOT EXISTS idx_absences_member_id ON absences(member_id);

CREATE TABLE IF NOT EXISTS event_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    name TEXT DEFAULT '',
    status TEXT DEFAULT '',
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_responses_event_id ON event_responses(event_id);
CREATE INDEX IF NOT EXISTS idx_event_responses_member_id ON event_responses(member_id);

CREATE TABLE IF NOT EXISTS date_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    deadline DATE,
    notes TEXT DEFAULT '',
    delete_phrase TEXT DEFAULT '',
    created_by TEXT DEFAULT '',
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_date_adjustments_deadline ON date_adjustments(deadline);
CREATE INDEX IF NOT EXISTS idx_date_adjustments_member_id ON date_adjustments(member_id);

CREATE TABLE IF NOT EXISTS date_adjustment_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_id BIGINT NOT NULL REFERENCES date_adjustments(id) ON DELETE CASCADE,
    candidate_key TEXT NOT NULL,
    date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    note TEXT DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (adjustment_id, candidate_key),
    UNIQUE (adjustment_id, date, start_time, end_time)
);

CREATE INDEX IF NOT EXISTS idx_date_adjustment_candidates_adjustment_id ON date_adjustment_candidates(adjustment_id);

CREATE TABLE IF NOT EXISTS date_adjustment_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_id BIGINT NOT NULL REFERENCES date_adjustments(id) ON DELETE CASCADE,
    candidate_key TEXT NOT NULL,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (status IN ('ok', 'maybe', 'ng'))
);

CREATE INDEX IF NOT EXISTS idx_date_adjustment_responses_adjustment_id ON date_adjustment_responses(adjustment_id);
CREATE INDEX IF NOT EXISTS idx_date_adjustment_responses_member_id ON date_adjustment_responses(member_id);

CREATE TABLE IF NOT EXISTS piece_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT REFERENCES performances(id) ON DELETE CASCADE,
    piece TEXT NOT NULL,
    description TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (performance_id, piece)
);

CREATE INDEX IF NOT EXISTS idx_piece_infos_performance_id ON piece_infos(performance_id);

CREATE TABLE IF NOT EXISTS practice_instructions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT REFERENCES performances(id) ON DELETE CASCADE,
    piece TEXT NOT NULL,
    practice_notes TEXT DEFAULT '',
    performance_instruction TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (performance_id, piece)
);

CREATE INDEX IF NOT EXISTS idx_practice_instructions_performance_id ON practice_instructions(performance_id);

CREATE TABLE IF NOT EXISTS castings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT REFERENCES performances(id) ON DELETE CASCADE,
    piece TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_castings_performance_id ON castings(performance_id);

CREATE TABLE IF NOT EXISTS casting_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    casting_id BIGINT NOT NULL REFERENCES castings(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    part TEXT DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_casting_members_casting_id ON casting_members(casting_id);
CREATE INDEX IF NOT EXISTS idx_casting_members_member_id ON casting_members(member_id);

CREATE TABLE IF NOT EXISTS casting_extras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    casting_id BIGINT NOT NULL REFERENCES castings(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    furigana TEXT DEFAULT '',
    part TEXT DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_casting_extras_casting_id ON casting_extras(casting_id);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    name TEXT DEFAULT '',
    paid_from_month CHAR(7) DEFAULT '',
    paid_until_month CHAR(7) DEFAULT '',
    latest_payment_date DATE,
    membership_fee_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (paid_from_month = '' OR paid_from_month ~ '^[0-9]{4}-[0-9]{2}$'),
    CHECK (paid_until_month = '' OR paid_until_month ~ '^[0-9]{4}-[0-9]{2}$')
);

CREATE INDEX IF NOT EXISTS idx_payments_member_id ON payments(member_id);

CREATE TABLE IF NOT EXISTS payment_performance_fees (
    payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    performance_id BIGINT NOT NULL REFERENCES performances(id) ON DELETE CASCADE,
    is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    fee_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (payment_id, performance_id)
);

CREATE TABLE IF NOT EXISTS desired_pieces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT DEFAULT '',
    piece TEXT DEFAULT '',
    composer TEXT DEFAULT '',
    duration TEXT DEFAULT '',
    genre TEXT DEFAULT '',
    formation TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    registered_by TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_desired_pieces_member_id ON desired_pieces(member_id);

CREATE TABLE IF NOT EXISTS desired_piece_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desired_piece_id BIGINT NOT NULL REFERENCES desired_pieces(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    name TEXT DEFAULT '',
    voted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_desired_piece_votes_piece_id ON desired_piece_votes(desired_piece_id);
CREATE INDEX IF NOT EXISTS idx_desired_piece_votes_member_id ON desired_piece_votes(member_id);

CREATE TABLE IF NOT EXISTS promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT DEFAULT '',
    image_url TEXT DEFAULT '',
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    registered_by TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_promotions_member_id ON promotions(member_id);
CREATE INDEX IF NOT EXISTS idx_promotions_created_at ON promotions(created_at DESC);

CREATE TABLE IF NOT EXISTS albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL,
    created_by_member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    created_by_member_name TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_albums_created_by_member_id ON albums(created_by_member_id);
CREATE INDEX IF NOT EXISTS idx_albums_created_at ON albums(created_at DESC);

CREATE TABLE IF NOT EXISTS album_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    url TEXT DEFAULT '',
    object_name TEXT DEFAULT '',
    path TEXT DEFAULT '',
    uploaded_by_member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    uploaded_by_member_name TEXT DEFAULT '',
    uploaded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_album_photos_album_id ON album_photos(album_id);
CREATE INDEX IF NOT EXISTS idx_album_photos_uploaded_by_member_id ON album_photos(uploaded_by_member_id);

CREATE TABLE IF NOT EXISTS part_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS venue_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT DEFAULT '',
    for_practice BOOLEAN NOT NULL DEFAULT TRUE,
    for_performance BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS org_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name TEXT DEFAULT '',
    organization_abbreviation TEXT DEFAULT '',
    short_name TEXT DEFAULT '',
    icon_url TEXT DEFAULT '',
    membership_fee_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sns_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_url TEXT DEFAULT '',
    x_url TEXT DEFAULT '',
    instagram_url TEXT DEFAULT '',
    youtube_url TEXT DEFAULT '',
    facebook_url TEXT DEFAULT '',
    website_url TEXT DEFAULT '',
    extra_links JSONB NOT NULL DEFAULT '[]'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS connection_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_project_id TEXT DEFAULT '',
    google_cloud_storage_bucket TEXT DEFAULT '',
    google_cloud_storage_data_prefix TEXT DEFAULT '',
    google_cloud_storage_public BOOLEAN,
    google_service_account_file TEXT DEFAULT '',
    google_service_account_json TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================
-- File metadata tables (non-binary)
-- =========================

CREATE TABLE IF NOT EXISTS drive_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT DEFAULT '',
    object_name TEXT DEFAULT '',
    path TEXT DEFAULT '',
    name TEXT DEFAULT '',
    url TEXT DEFAULT '',
    size_bytes BIGINT,
    mime_type TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_drive_files_object_name ON drive_files(object_name);

CREATE TABLE IF NOT EXISTS recording_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT DEFAULT '',
    object_name TEXT DEFAULT '',
    path TEXT DEFAULT '',
    name TEXT DEFAULT '',
    date DATE,
    piece TEXT DEFAULT '',
    duration_seconds NUMERIC(12, 3),
    duration TEXT DEFAULT '',
    mime_type TEXT DEFAULT '',
    size_bytes BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recording_metadata_object_name ON recording_metadata(object_name);
CREATE INDEX IF NOT EXISTS idx_recording_metadata_path ON recording_metadata(path);

CREATE TABLE IF NOT EXISTS sheet_library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT REFERENCES performances(id) ON DELETE SET NULL,
    performance_title TEXT DEFAULT '',
    piece TEXT DEFAULT '',
    part TEXT DEFAULT '',
    source TEXT DEFAULT '',
    name TEXT DEFAULT '',
    path TEXT DEFAULT '',
    object_name TEXT DEFAULT '',
    url TEXT DEFAULT '',
    view_url TEXT DEFAULT '',
    download_url TEXT DEFAULT '',
    size_bytes BIGINT,
    mime_type TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sheet_library_performance_id ON sheet_library(performance_id);
CREATE INDEX IF NOT EXISTS idx_sheet_library_object_name ON sheet_library(object_name);

COMMIT;
