from __future__ import annotations

from typing import Any

from ..core.db_pool import pooled_psycopg as psycopg
from psycopg import sql as psql


class SystemRepository:
    """PostgreSQL read/write repository for system administration APIs."""

    def __init__(self, conn_str: str) -> None:
        self._conn_str = conn_str

    def list_tables(self, portal_tables: set[str]) -> list[str]:
        with psycopg.connect(self._conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    (
                        "SELECT table_name "
                        "FROM information_schema.tables "
                        "WHERE table_schema = 'public' AND table_type = 'BASE TABLE' "
                        "ORDER BY table_name"
                    )
                )
                return [str(row[0]) for row in cur.fetchall() if str(row[0]) in portal_tables]

    def list_table_records(self, table: str, limit: int, offset: int) -> tuple[list[str], list[tuple[Any, ...]], int]:
        with psycopg.connect(self._conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    (
                        "SELECT column_name "
                        "FROM information_schema.columns "
                        "WHERE table_schema = 'public' AND table_name = %s "
                        "ORDER BY ordinal_position"
                    ),
                    (table,),
                )
                columns = [str(row[0]) for row in cur.fetchall()]
                if not columns:
                    return [], [], 0

                cur.execute(psql.SQL("SELECT COUNT(*) FROM {}; ").format(psql.Identifier(table)))
                total = int(cur.fetchone()[0])

                order_clause = psql.SQL(" ORDER BY {} DESC").format(psql.Identifier("id")) if "id" in columns else psql.SQL("")
                query = psql.SQL("SELECT * FROM {}{} LIMIT %s OFFSET %s;").format(psql.Identifier(table), order_clause)
                cur.execute(query, (limit, offset))
                rows = cur.fetchall()
                description = cur.description or []
                column_names = [str(desc.name) for desc in description]
                return column_names, rows, total

    def list_migrations(self, limit: int, offset: int) -> tuple[list[dict[str, Any]], int]:
        with psycopg.connect(self._conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS schema_migrations (
                        version TEXT PRIMARY KEY,
                        name TEXT NOT NULL,
                        checksum TEXT NOT NULL,
                        applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
                cur.execute("SELECT COUNT(*) FROM schema_migrations")
                total = int(cur.fetchone()[0])
                cur.execute(
                    """
                    SELECT version, name, checksum, applied_at
                    FROM schema_migrations
                    ORDER BY version DESC
                    LIMIT %s OFFSET %s
                    """,
                    (limit, offset),
                )
                rows = [
                    {
                        "version": str(row[0]),
                        "name": str(row[1]),
                        "checksum": str(row[2]),
                        "applied_at": row[3].isoformat() if row[3] else "",
                    }
                    for row in cur.fetchall()
                ]
                return rows, total

    def list_audit_logs(
        self,
        limit: int,
        offset: int,
        actor_device_id: str = "",
        path: str = "",
    ) -> tuple[list[dict[str, Any]], int]:
        conditions = []
        params: list[Any] = []
        if actor_device_id:
            conditions.append("actor_device_id = %s")
            params.append(actor_device_id)
        if path:
            conditions.append("path ILIKE %s")
            params.append(f"%{path}%")
        where_sql = " WHERE " + " AND ".join(conditions) if conditions else ""

        with psycopg.connect(self._conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS audit_logs (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        actor_device_id TEXT DEFAULT '',
                        actor_member_id BIGINT NULL,
                        actor_member_name TEXT DEFAULT '',
                        actor_permission TEXT DEFAULT '',
                        action TEXT NOT NULL,
                        method TEXT NOT NULL,
                        path TEXT NOT NULL,
                        status_code INTEGER,
                        target_table TEXT DEFAULT '',
                        target_id TEXT DEFAULT '',
                        request_id TEXT DEFAULT '',
                        user_agent TEXT DEFAULT '',
                        ip_address TEXT DEFAULT '',
                        detail JSONB NOT NULL DEFAULT '{}'::jsonb,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
                cur.execute(f"SELECT COUNT(*) FROM audit_logs{where_sql}", tuple(params))
                total = int(cur.fetchone()[0])
                cur.execute(
                    f"""
                    SELECT id, actor_device_id, actor_member_id, actor_member_name, actor_permission,
                           action, method, path, status_code, target_table, target_id, request_id,
                           user_agent, ip_address, detail, created_at
                    FROM audit_logs{where_sql}
                    ORDER BY created_at DESC
                    LIMIT %s OFFSET %s
                    """,
                    tuple(params + [limit, offset]),
                )
                rows = []
                for row in cur.fetchall():
                    rows.append(
                        {
                            "id": row[0],
                            "actor_device_id": row[1],
                            "actor_member_id": row[2],
                            "actor_member_name": row[3],
                            "actor_permission": row[4],
                            "action": row[5],
                            "method": row[6],
                            "path": row[7],
                            "status_code": row[8],
                            "target_table": row[9],
                            "target_id": row[10],
                            "request_id": row[11],
                            "user_agent": row[12],
                            "ip_address": row[13],
                            "detail": row[14],
                            "created_at": row[15].isoformat() if row[15] else "",
                        }
                    )
                return rows, total

    def list_role_permissions(self) -> list[dict[str, Any]]:
        with psycopg.connect(self._conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS role_permissions (
                        role_name TEXT NOT NULL,
                        permission_key TEXT NOT NULL,
                        enabled BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                        PRIMARY KEY (role_name, permission_key)
                    )
                    """
                )
                cur.execute(
                    """
                    SELECT role_name, permission_key, enabled, updated_at
                    FROM role_permissions
                    ORDER BY role_name, permission_key
                    """
                )
                return [
                    {
                        "role_name": row[0],
                        "permission_key": row[1],
                        "enabled": bool(row[2]),
                        "updated_at": row[3].isoformat() if row[3] else "",
                    }
                    for row in cur.fetchall()
                ]

    def upsert_role_permission(self, role_name: str, permission_key: str, enabled: bool) -> None:
        with psycopg.connect(self._conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO role_permissions (role_name, permission_key, enabled, updated_at)
                    VALUES (%s, %s, %s, NOW())
                    ON CONFLICT (role_name, permission_key)
                    DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = NOW()
                    """,
                    (role_name, permission_key, enabled),
                )

    def record_cache_invalidation(self, cache_key: str, reason: str) -> None:
        with psycopg.connect(self._conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS cache_invalidation_events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cache_key TEXT NOT NULL,
                        reason TEXT DEFAULT '',
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """
                )
                cur.execute(
                    "INSERT INTO cache_invalidation_events (cache_key, reason) VALUES (%s, %s)",
                    (cache_key, reason),
                )
